-- 001_core: the complete Phase-1 schema.
--
-- Content tables (revisions, annotations) are immutable: triggers abort any
-- UPDATE or DELETE. Mutable moderation state lives in separate *_review tables,
-- and every moderation decision is an append-only moderation_events row.
-- The restricted purge for leaked secrets / personal data (SPEC.md) is a later,
-- deliberate procedure; it is not an ordinary operation and has no API.
--
-- Timestamps are ISO-8601 UTC strings with milliseconds, generated by the
-- application so they can be included in content hashes.

CREATE TABLE contributors (
  id            TEXT PRIMARY KEY CHECK (id LIKE 'ctr\_%' ESCAPE '\'),
  display_name  TEXT NOT NULL CHECK (length(display_name) BETWEEN 1 AND 80),
  role          TEXT NOT NULL CHECK (role IN ('contributor', 'steward')),
  client_info   TEXT NOT NULL DEFAULT '{}'
                CHECK (json_valid(client_info) AND json_type(client_info) = 'object'),
  disabled_at   TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);

CREATE TABLE credentials (
  id              TEXT PRIMARY KEY CHECK (id LIKE 'cred\_%' ESCAPE '\'),
  contributor_id  TEXT NOT NULL REFERENCES contributors(id),
  token_prefix    TEXT NOT NULL UNIQUE,
  secret_hash     TEXT NOT NULL,
  scopes          TEXT NOT NULL CHECK (json_valid(scopes) AND json_type(scopes) = 'array'),
  label           TEXT,
  created_at      TEXT NOT NULL,
  revoked_at      TEXT
);
CREATE INDEX credentials_contributor ON credentials(contributor_id);

-- Defense in depth: the 'moderate' scope can only ever sit on a steward.
-- The application never offers it to anyone else; this makes that true even
-- if application code is wrong.
CREATE TRIGGER credentials_moderate_requires_steward
BEFORE INSERT ON credentials
WHEN EXISTS (SELECT 1 FROM json_each(NEW.scopes) WHERE value = 'moderate')
 AND (SELECT role FROM contributors WHERE id = NEW.contributor_id) IS NOT 'steward'
BEGIN
  SELECT RAISE(ABORT, 'moderate scope requires a steward contributor');
END;

-- A credential may be revoked (revoked_at set once); nothing else about it changes.
CREATE TRIGGER credentials_only_revocation
BEFORE UPDATE ON credentials
WHEN NEW.id IS NOT OLD.id
  OR NEW.contributor_id IS NOT OLD.contributor_id
  OR NEW.token_prefix IS NOT OLD.token_prefix
  OR NEW.secret_hash IS NOT OLD.secret_hash
  OR NEW.scopes IS NOT OLD.scopes
  OR NEW.created_at IS NOT OLD.created_at
  OR (OLD.revoked_at IS NOT NULL AND NEW.revoked_at IS NOT OLD.revoked_at)
BEGIN
  SELECT RAISE(ABORT, 'credentials can only be revoked, not modified');
END;

CREATE TABLE records (
  id                   TEXT PRIMARY KEY CHECK (id LIKE 'rec\_%' ESCAPE '\'),
  slug                 TEXT NOT NULL UNIQUE CHECK (length(slug) BETWEEN 1 AND 100),
  current_revision_id  TEXT REFERENCES revisions(id),
  created_by           TEXT NOT NULL REFERENCES contributors(id),
  created_at           TEXT NOT NULL,
  updated_at           TEXT NOT NULL
);

-- Stable identity: a record's id, slug, creator and creation time never change.
CREATE TRIGGER records_identity_immutable
BEFORE UPDATE ON records
WHEN NEW.id IS NOT OLD.id
  OR NEW.slug IS NOT OLD.slug
  OR NEW.created_by IS NOT OLD.created_by
  OR NEW.created_at IS NOT OLD.created_at
BEGIN
  SELECT RAISE(ABORT, 'record identity is immutable');
END;

CREATE TRIGGER records_no_delete
BEFORE DELETE ON records
BEGIN
  SELECT RAISE(ABORT, 'records are not deleted; use moderation and tombstones');
END;

CREATE TABLE revisions (
  id                  TEXT PRIMARY KEY CHECK (id LIKE 'rev\_%' ESCAPE '\'),
  record_id           TEXT NOT NULL REFERENCES records(id),
  base_revision_id    TEXT REFERENCES revisions(id),
  parent_revision_id  TEXT REFERENCES revisions(id),
  author_id           TEXT NOT NULL REFERENCES contributors(id),
  kind                TEXT NOT NULL CHECK (kind IN
                        ('observation', 'claim', 'hypothesis', 'procedure',
                         'experiment_result', 'synthesis')),
  title               TEXT NOT NULL,
  summary             TEXT NOT NULL,
  body_markdown       TEXT NOT NULL,
  tags                TEXT NOT NULL DEFAULT '[]'
                      CHECK (json_valid(tags) AND json_type(tags) = 'array'),
  sources             TEXT NOT NULL DEFAULT '[]'
                      CHECK (json_valid(sources) AND json_type(sources) = 'array'),
  conditions          TEXT NOT NULL DEFAULT '{}'
                      CHECK (json_valid(conditions) AND json_type(conditions) = 'object'),
  links               TEXT NOT NULL DEFAULT '[]'
                      CHECK (json_valid(links) AND json_type(links) = 'array'),
  content_license     TEXT NOT NULL,
  hash_schema         TEXT NOT NULL,
  content_hash        TEXT NOT NULL CHECK (content_hash LIKE 'sha256:%'),
  created_at          TEXT NOT NULL
);
CREATE INDEX revisions_record ON revisions(record_id, id);

-- base and parent must belong to the same record as the new revision.
CREATE TRIGGER revisions_lineage_same_record
BEFORE INSERT ON revisions
WHEN (NEW.base_revision_id IS NOT NULL AND
      (SELECT record_id FROM revisions WHERE id = NEW.base_revision_id) IS NOT NEW.record_id)
  OR (NEW.parent_revision_id IS NOT NULL AND
      (SELECT record_id FROM revisions WHERE id = NEW.parent_revision_id) IS NOT NEW.record_id)
BEGIN
  SELECT RAISE(ABORT, 'base/parent revision belongs to a different record');
END;

CREATE TRIGGER revisions_no_update
BEFORE UPDATE ON revisions
BEGIN
  SELECT RAISE(ABORT, 'revisions are immutable');
END;

CREATE TRIGGER revisions_no_delete
BEFORE DELETE ON revisions
BEGIN
  SELECT RAISE(ABORT, 'revisions are immutable');
END;

-- The published pointer may only name a revision of this same record.
CREATE TRIGGER records_current_revision_same_record
BEFORE UPDATE OF current_revision_id ON records
WHEN NEW.current_revision_id IS NOT NULL
 AND (SELECT record_id FROM revisions WHERE id = NEW.current_revision_id) IS NOT NEW.id
BEGIN
  SELECT RAISE(ABORT, 'current revision belongs to a different record');
END;

CREATE TABLE revision_review (
  revision_id  TEXT PRIMARY KEY REFERENCES revisions(id),
  state        TEXT NOT NULL CHECK (state IN
                 ('candidate', 'reviewed', 'quarantined', 'rejected', 'superseded')),
  reason       TEXT,
  updated_at   TEXT NOT NULL
);

CREATE TABLE annotations (
  id                        TEXT PRIMARY KEY CHECK (id LIKE 'ann\_%' ESCAPE '\'),
  revision_id               TEXT NOT NULL REFERENCES revisions(id),
  author_id                 TEXT NOT NULL REFERENCES contributors(id),
  kind                      TEXT NOT NULL CHECK (kind IN
                              ('critique', 'question', 'usefulness',
                               'correction_note', 'outcome_report')),
  outcome                   TEXT CHECK (outcome IN
                              ('worked', 'failed', 'partially_worked',
                               'not_applicable', 'inconclusive')),
  body                      TEXT NOT NULL,
  evidence                  TEXT NOT NULL DEFAULT '[]'
                            CHECK (json_valid(evidence) AND json_type(evidence) = 'array'),
  conditions                TEXT NOT NULL DEFAULT '{}'
                            CHECK (json_valid(conditions) AND json_type(conditions) = 'object'),
  supersedes_annotation_id  TEXT REFERENCES annotations(id),
  hash_schema               TEXT NOT NULL,
  content_hash              TEXT NOT NULL CHECK (content_hash LIKE 'sha256:%'),
  created_at                TEXT NOT NULL,
  -- An outcome is present exactly when the annotation is an outcome report.
  CHECK ((kind = 'outcome_report') = (outcome IS NOT NULL))
);
CREATE INDEX annotations_revision ON annotations(revision_id, id);

-- A superseding annotation replaces the same author's earlier annotation on the
-- same exact revision. It never moves a report to a different revision.
CREATE TRIGGER annotations_supersede_same_author_and_revision
BEFORE INSERT ON annotations
WHEN NEW.supersedes_annotation_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM annotations
                 WHERE id = NEW.supersedes_annotation_id
                   AND revision_id = NEW.revision_id
                   AND author_id = NEW.author_id)
BEGIN
  SELECT RAISE(ABORT, 'superseded annotation must be your own, on the same revision');
END;

CREATE TRIGGER annotations_no_update
BEFORE UPDATE ON annotations
BEGIN
  SELECT RAISE(ABORT, 'annotations are immutable');
END;

CREATE TRIGGER annotations_no_delete
BEFORE DELETE ON annotations
BEGIN
  SELECT RAISE(ABORT, 'annotations are immutable');
END;

CREATE TABLE annotation_review (
  annotation_id  TEXT PRIMARY KEY REFERENCES annotations(id),
  state          TEXT NOT NULL CHECK (state IN
                   ('candidate', 'reviewed', 'quarantined', 'rejected', 'superseded')),
  reason         TEXT,
  updated_at     TEXT NOT NULL
);

CREATE TABLE moderation_events (
  id           TEXT PRIMARY KEY CHECK (id LIKE 'mod\_%' ESCAPE '\'),
  actor_id     TEXT NOT NULL REFERENCES contributors(id),
  target_type  TEXT NOT NULL CHECK (target_type IN
                 ('record', 'revision', 'annotation', 'contributor', 'credential')),
  target_id    TEXT NOT NULL,
  action       TEXT NOT NULL,
  reason       TEXT NOT NULL CHECK (length(reason) >= 1),
  created_at   TEXT NOT NULL
);
CREATE INDEX moderation_events_target ON moderation_events(target_type, target_id);

CREATE TRIGGER moderation_events_no_update
BEFORE UPDATE ON moderation_events
BEGIN
  SELECT RAISE(ABORT, 'moderation events are append-only');
END;

CREATE TRIGGER moderation_events_no_delete
BEFORE DELETE ON moderation_events
BEGIN
  SELECT RAISE(ABORT, 'moderation events are append-only');
END;

CREATE TABLE idempotency_keys (
  contributor_id   TEXT NOT NULL REFERENCES contributors(id),
  operation        TEXT NOT NULL,
  key              TEXT NOT NULL CHECK (length(key) BETWEEN 1 AND 200),
  request_hash     TEXT NOT NULL,
  response_status  INTEGER NOT NULL,
  response_body    TEXT NOT NULL CHECK (json_valid(response_body)),
  created_at       TEXT NOT NULL,
  expires_at       TEXT NOT NULL,
  PRIMARY KEY (contributor_id, operation, key)
);
CREATE INDEX idempotency_keys_expiry ON idempotency_keys(expires_at);
